import type {
  GifterLevel,
  GifterPathConfig,
  GifterPathGenerationOptions,
  GifterProgress,
  IdentityLabel,
} from './types.js';

const MIN_LEVELS = 3;
const MAX_LEVELS = 50;
const DEFAULT_GROWTH = 1.8;

const RANK_NAMES = ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Mythic'];
const FANTASY_NAMES = ['Adventurer', 'Mage', 'Knight', 'Dragon Rider', 'Archon', 'Elder'];
const SCIFI_NAMES = ['Cadet', 'Pilot', 'Commander', 'Captain', 'Admiral', 'Ascendant'];

export function generateGifterPathConfig(opts: GifterPathGenerationOptions): GifterPathConfig {
  const levelCount = clamp(Math.round(opts.levelCount), MIN_LEVELS, MAX_LEVELS);
  const growth = opts.growthFactor && opts.growthFactor > 1 ? opts.growthFactor : DEFAULT_GROWTH;

  const levels: GifterLevel[] = [];
  let threshold = Math.max(1, Math.floor(opts.baseThresholdMinor));

  for (let i = 0; i < levelCount; i++) {
    const index = i + 1;
    const thresholdMinor = i === 0 ? threshold : Math.floor(threshold * growth);
    threshold = thresholdMinor;

    const name = getLevelName(opts.namingPreset, index, levelCount);

    levels.push({
      id: `lvl-${index}`,
      index,
      thresholdMinor,
      currency: opts.currency,
      name,
    });
  }

  return {
    id: `gpath-${Date.now()}`,
    creatorId: undefined,
    currency: opts.currency,
    levels,
    namingPreset: opts.namingPreset,
    iconTheme: opts.iconTheme,
    colorTheme: opts.colorTheme,
    displayThemeName: opts.displayThemeName,
  };
}

export function computeGifterProgress(config: GifterPathConfig, totalSupportMinor: number): GifterProgress {
  const sortedLevels = [...config.levels].sort((a, b) => a.thresholdMinor - b.thresholdMinor);
  const unlockedLevels = sortedLevels.filter((lvl) => totalSupportMinor >= lvl.thresholdMinor);
  const currentLevel = unlockedLevels[unlockedLevels.length - 1];
  const nextLevel = sortedLevels.find((lvl) => !currentLevel || lvl.thresholdMinor > currentLevel.thresholdMinor);

  let progressToNext = 0;
  if (!nextLevel) {
    // Max level reached; treat as 100%.
    progressToNext = 1;
  } else {
    const prevThreshold = currentLevel?.thresholdMinor ?? 0;
    const span = nextLevel.thresholdMinor - prevThreshold;
    const gained = totalSupportMinor - prevThreshold;
    progressToNext = span > 0 ? clamp(gained / span, 0, 1) : 0;
  }

  return {
    totalSupportMinor,
    currency: config.currency,
    currentLevel,
    nextLevel,
    progressToNext,
    unlockedLevels,
  };
}

export function generateIdentityLabel(subjectId: string): IdentityLabel {
  const normalized = subjectId.trim();
  if (!normalized) {
    return {
      subjectId,
      displayName: 'Guest',
      isAutoGenerated: true,
    };
  }

  const hash = simpleHash(normalized);
  const adjectives = ['Cozy', 'Electric', 'Quantum', 'Crimson', 'Aurora', 'Nebula', 'Pixel', 'Solar', 'Lunar', 'Velvet'];
  const nouns = ['Comet', 'Dragon', 'Phoenix', 'Voyager', 'Ranger', 'Beacon', 'Golem', 'Sprite', 'Guardian', 'Rider'];

  const adjective = adjectives[hash % adjectives.length];
  const noun = nouns[(hash >> 4) % nouns.length];
  const suffix = (hash % 1000).toString().padStart(3, '0');

  return {
    subjectId,
    displayName: `${adjective} ${noun} #${suffix}`,
    isAutoGenerated: true,
  };
}

function getLevelName(preset: GifterPathConfig['namingPreset'], index: number, total: number): string {
  const baseIndex = index - 1;
  switch (preset) {
    case 'ranks':
      return RANK_NAMES[Math.min(baseIndex, RANK_NAMES.length - 1)] + ` L${index}`;
    case 'fantasy':
      return FANTASY_NAMES[Math.min(baseIndex, FANTASY_NAMES.length - 1)] + ` ${index}`;
    case 'sci-fi':
      return SCIFI_NAMES[Math.min(baseIndex, SCIFI_NAMES.length - 1)] + ` ${index}`;
    case 'custom':
    default:
      return `Level ${index}/${total}`;
  }
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function simpleHash(input: string): number {
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    hash = (hash * 31 + input.charCodeAt(i)) >>> 0;
  }
  return hash;
}

export type { GifterLevel, GifterPathConfig, GifterPathGenerationOptions, GifterProgress, IdentityLabel } from './types.js';
