export type GifterNamingPreset = 'ranks' | 'fantasy' | 'sci-fi' | 'custom';

export type GifterIconTheme = 'minimal' | 'emoji' | 'badges';

export type GifterColorTheme = 'pastel' | 'vibrant' | 'dark';

export interface GifterLevel {
  id: string;
  index: number;
  /** Inclusive threshold in minor units (e.g. cents). */
  thresholdMinor: number;
  currency: string;
  name: string;
  description?: string;
  icon?: string;
  color?: string;
  perks?: string[];
}

export interface GifterPathConfig {
  id: string;
  creatorId?: string;
  currency: string;
  levels: GifterLevel[];
  namingPreset: GifterNamingPreset;
  iconTheme: GifterIconTheme;
  colorTheme: GifterColorTheme;
  /** Optional raw theme name for display (e.g. "Galaxy Guild"). */
  displayThemeName?: string;
}

export interface GifterProgress {
  totalSupportMinor: number;
  currency: string;
  currentLevel?: GifterLevel;
  nextLevel?: GifterLevel;
  /** 0-1 fraction towards next level, or 1 if maxed. */
  progressToNext: number;
  /** All levels whose threshold has been met. */
  unlockedLevels: GifterLevel[];
}

export interface GifterPathGenerationOptions {
  currency: string;
  levelCount: number; // 3-50
  /** Base threshold for level 1 in minor units. */
  baseThresholdMinor: number;
  /** Multiplier applied per level, e.g. 1.8 for exponential-ish growth. */
  growthFactor?: number;
  namingPreset: GifterNamingPreset;
  iconTheme: GifterIconTheme;
  colorTheme: GifterColorTheme;
  displayThemeName?: string;
}

export interface IdentityLabel {
  /** Stable internal id, e.g. wallet hash or viewer id. */
  subjectId: string;
  /** Display name shown in UI. */
  displayName: string;
  /** True if this was auto-generated from an anonymous subject. */
  isAutoGenerated: boolean;
}
